### ISSUE TITLE
Installation/Configuration Issue - Complaining about tshark???

### ISSUE THREAD

**Issue by georgiabasser** [applied-risk/snmpv3brute#2]
Kali 2021.3 Rolling. Installed snmpv3brute. Initially had errors with pyshark. Installed pyshark. Now getting errors about tshark. Not sure what I did wrong but it's got to be me as I don't see any other posts with this error. Any help is much appreciated.

root:/home/pentester/app/snmpv3brute# python3 snmpv3brute.py -p /home/pentester/popular/packets.pcap -w /home/pentester/app/wordlists/rc-passwords.txt
                                ____  _                _
                               |___ \| |              | |
  ___ _ __  _ __ ___  _ ____   ____) | |__  _ __ _   _| |_ ___
 / __| '_ \| '_ ` _ \| '_ \ \ / /__ <| '_ \| '__| | | | __/ _ \
 \__ \ | | | | | | | | |_) \ V /___) | |_) | |  | |_| | ||  __/
 |___/_| |_|_| |_| |_| .__/ \_/|____/|_.__/|_|   \__,_|\__\___|
                     | |        by Scott Thomas
                     |_|           for Applied Risk

Looking for SNMPv3 packets in /home/pentester/popular/packets.pcap...
Traceback (most recent call last):
  File "/home/pentester/app/snmpv3brute/snmpv3brute.py", line 299, in <module>
    main()
  File "/home/pentester/app/snmpv3brute/snmpv3brute.py", line 214, in main
    taskList=process_packets(args.pcapFile)
  File "/home/pentester/app/snmpv3brute/snmpv3brute.py", line 96, in process_packets
    for pkt in cap:
  File "/usr/local/lib/python3.9/dist-packages/pyshark/capture/capture.py", line 232, in _packets_from_tshark_sync
    tshark_process = existing_process or self.eventloop.run_until_complete(self._get_tshark_process())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/pyshark/capture/capture.py", line 389, in _get_tshark_process
    if not tshark_supports_json(self._get_tshark_version()):
  File "/usr/local/lib/python3.9/dist-packages/pyshark/capture/capture.py", line 381, in _get_tshark_version
    self.__tshark_version = get_tshark_version(self.tshark_path)
  File "/usr/local/lib/python3.9/dist-packages/pyshark/tshark/tshark.py", line 65, in get_tshark_version
    parameters = [get_process_path(tshark_path), "-v"]
  File "/usr/local/lib/python3.9/dist-packages/pyshark/tshark/tshark.py", line 58, in get_process_path
    raise TSharkNotFoundException(
pyshark.tshark.tshark.TSharkNotFoundException: TShark not found. Try adding its location to the configuration file. Searched these paths: ['C:\\Program Files\\Wireshark\\tshark.exe', '/usr/local/sbin/tshark', '/usr/local/bin/tshark', '/usr/sbin/tshark', '/usr/bin/tshark', '/sbin/tshark', '/bin/tshark', '/usr/games/tshark', '/usr/local/games/tshark', '/snap/bin/tshark']
root@do-sentinel-009:/home/pentester/app/snmpv3brute#

**Comment by georgiabasser** [comment]
Please close out issue. I was able to install tshark separately and I believe everything is working as expected. I look forward to using this script effectively against snmpv3 targets. Thanks for sharing.
